name: PR Reviewer

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    if: github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Reviewer
        uses: ./
        