name: PR Reviewer

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install dependencies
        run: npm install

      - name: Build                 # ✅ ADD THIS
        run: npm run build

      - name: Run Reviewer
        uses: ./
        with:
          groq_api_key: ${{ secrets.GROQ_API_KEY }}
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 